# ruff: noqa: E501
"""Inspectable official-TRAIN flight recordings, source labels and live pilot status."""

import base64
import io
import json
from pathlib import Path

from PIL import Image

ROOT = Path("D:/drone_vla_pilot/data/openfly_train_pilot_20260917")
VIEW = Path("reports/vla_dataset_review_20260916")
rows = [json.loads(x) for x in (ROOT / "index.jsonl").read_text().splitlines()]
for row in rows:
    with Image.open(row["images"][-1]) as image:
        image = image.convert("RGB")
        image.thumbnail((480, 320))
        buffer = io.BytesIO()
        image.save(buffer, format="JPEG", quality=75)
    row["preview"] = "data:image/jpeg;base64," + base64.b64encode(buffer.getvalue()).decode()
data = json.dumps(rows).replace("</", "<\\/")
html = """<!doctype html><html><meta charset="utf-8"><title>OpenFly TRAIN pilot</title><style>
body{background:#101c2a;color:#e4edf7;font:18px system-ui;margin:30px}a{color:#72c6ff}section{background:#1c2d40;padding:20px;margin:16px 0;border-radius:12px}select,button,input{font:inherit;max-width:95%}img{width:480px;max-width:100%}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px monospace}canvas{background:#142335;max-width:100%}.grid{display:flex;gap:24px;flex-wrap:wrap}</style>
<h1>OpenFly: source trajectories and native-action pilot</h1><a href="expanded_models.html">Previous comparison</a>
<p>OpenFly integration diagnosis: re-decoding identical saved model tokens using the released evaluator normalization changes coarse accuracy from 12/51 to 29/51. Mixed vectors disappear, but turns remain 0/12. This is post-hoc decoder sensitivity, not new inference or flight success. The original comparison remains unchanged.</p>
<p>22 recorded expert trajectories from official TRAIN only: 11 training, 11 development. These are dataset simulator/reconstructed-scene recordings, not flights generated by our model. No physical drone recordings were added in this pilot; no live drone feed.</p>
<section><h2>Training status</h2><p id="status">Preparing local pilot</p><p>SmolVLM-500M, fresh language LoRA. First memorize eight TRAIN examples; only if ≥7/8 exact, reset to base and run 160 updates with mixed action classes. No AWS. New native-ID policy, separate from FRD baselines.</p><canvas id="loss" width="850" height="210"></canvas><pre id="metrics"></pre></section>
<section><h2>Recorded route and model predictions</h2><select id="trajectory"></select><p id="instruction"></p><button id="play">Play source frames</button> <input id="step" type="range" min="0" value="0"><span id="counter"></span><div class="grid"><img id="frame"><canvas id="route" width="400" height="320"></canvas></div><p id="label"></p><pre id="prediction"></pre><details><summary>Exact source/provenance</summary><pre id="source"></pre></details></section>
<p>Pilot outcome: 8/8 memorization passed; fresh160-update adapter gets18/171 exact dev actions, macro recall0.149, below majority113/171 and macro0.167. Blank images produce11/171 (all STOP).26false STOPs on160nonterminal decisions. Pipeline works; useful flight competence is not established. These171exact-ID cases differ from the earlier51coarse-category OpenFly cases and are not a head-to-head model comparison.</p>
<p>Motion audit: 910/911 raw consecutive transitions match the expected atomic motion; one zero-motion turn is flagged. Compressed annotation frame gaps are not fixed action durations (all22 ID8 gaps are3 source units, despite the dictionary label6). This pilot imitates released IDs only; physical control mapping remains unverified.</p>
<p>Native IDs: 0 stop; 1/8/9 forward 3/6/9 m; 2 left turn; 3 right turn; 4 up; 5 down; 6/7 lateral left/right (absent in this data). Turn/vertical execution units require reconciliation before simulator control. The development subset has no up/down labels; it cannot establish vertical generalization.</p>
<p>Training uses only two preceding frames plus current, instruction, and target ID. Displayed positions are recording metadata, never model inputs. Up to 256px per model image. No official evaluation trajectories used. This small subset tests the data pipeline; it is not enough for deployment.</p>
<script>const ROWS=__DATA__;let REPORT={},LOG=[],timer=null;const el=id=>document.getElementById(id);const paths=[...new Set(ROWS.map(r=>r.trajectory))];for(const p of paths){const r=ROWS.find(r=>r.trajectory===p),o=document.createElement('option');o.value=p;o.textContent=r.split+' | '+p;el('trajectory').append(o)}
function selected(){return ROWS.filter(r=>r.trajectory===el('trajectory').value)}
function draw(){const rs=selected();el('step').max=rs.length-1;const i=Math.min(+el('step').value,rs.length-1),r=rs[i];el('instruction').textContent=r.instruction;el('frame').src=r.preview;el('counter').textContent=` ${i+1}/${rs.length}`;el('label').textContent=`Recorded expert action: ${r.action_id} — ${r.action_name}`;const {preview,...source}=r;el('source').textContent=JSON.stringify(source,null,2);const p=(REPORT.dev_after||REPORT.overfit_after||[]).find(x=>x.id===r.id);el('prediction').textContent=p?'Model output: '+JSON.stringify(p,null,2):'No saved model prediction for this frame yet.';const c=el('route').getContext('2d');c.clearRect(0,0,400,320);const xs=rs.map(r=>r.position[0]),ys=rs.map(r=>r.position[1]);const x=v=>20+360*(v-Math.min(...xs))/(Math.max(...xs)-Math.min(...xs)||1),y=v=>300-280*(v-Math.min(...ys))/(Math.max(...ys)-Math.min(...ys)||1);c.strokeStyle='#70bcfa';c.beginPath();rs.forEach((r,j)=>j?c.lineTo(x(r.position[0]),y(r.position[1])):c.moveTo(x(r.position[0]),y(r.position[1])));c.stroke();c.fillStyle='#ffca66';c.beginPath();c.arc(x(r.position[0]),y(r.position[1]),6,0,Math.PI*2);c.fill()}
function plot(){const c=el('loss').getContext('2d');c.clearRect(0,0,850,210);if(!LOG.length)return;const max=Math.max(...LOG.map(x=>x.loss),.1);c.fillStyle='#e4edf7';c.fillText('Training loss per update · orange overfit / blue fresh pilot · stages have different samples',12,15);for(const stage of ['overfit','pilot']){const a=LOG.filter(x=>x.stage===stage);c.strokeStyle=stage==='overfit'?'#ffca66':'#70bcfa';c.beginPath();a.forEach((r,i)=>{const x=35+(r.step-1)/160*790,y=190-r.loss/max*160;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()}c.fillText('0',15,192);c.fillText(max.toFixed(2),5,35);c.fillText('160 updates',740,207)}
async function refresh(){try{const x=await fetch('openfly_training_status.json?t='+Date.now());if(x.ok){const d=await x.json();REPORT=d.report;LOG=d.losses;el('status').textContent=REPORT.status+' · '+(REPORT.updates||0)+' updates in current stage';const out={};for(const k of ['overfit_before','overfit_after','dev_before','dev_after','dev_blank_images'])if(REPORT[k])out[k]={exact:REPORT[k].filter(p=>p.exact).length,n:REPORT[k].length,...(REPORT.metrics?.[k]?{invalid:REPORT.metrics[k].invalid,macro_recall:REPORT.metrics[k].macro_recall.toFixed(3),majority_correct:REPORT.metrics[k].majority_correct}:{})};el('metrics').textContent=JSON.stringify(out,null,2);plot();draw()}}catch(e){el('status').textContent='Status unavailable; inspect training log.'}}
el('trajectory').onchange=()=>{el('step').value=0;draw()};el('step').oninput=draw;el('play').onclick=()=>{if(timer){clearInterval(timer);timer=null;el('play').textContent='Play source frames'}else{timer=setInterval(()=>{el('step').value=(+el('step').value+1)%selected().length;draw()},650);el('play').textContent='Pause'}};draw();refresh();setInterval(refresh,10000);
</script></html>""".replace("__DATA__", data)
(VIEW / "openfly_training.html").write_text(html, encoding="utf-8")
print(
    json.dumps(
        dict(
            page=str(VIEW / "openfly_training.html"),
            trajectories=len(set(r["trajectory"] for r in rows)),
            rows=len(rows),
        )
    )
)
